name: Clean

on:
  push:
    branches: ["main"]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # So we can test on forks
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.3

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Code Linting
        run: pnpm lint
